# -*- coding: utf-8 -*-
"""ML A3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2vScXMZ1F8b-VQyWNNAx23r0MRQI8Uq
"""

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# Fetch dataset
bank_marketing = fetch_ucirepo(id=222)

# Features and target
X = bank_marketing.data.features
y = bank_marketing.data.targets['y'].map({'yes': 1, 'no': 0})

# Metadata (optional)
print(bank_marketing.metadata)

# Variable information (optional)
print(bank_marketing.variables)

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve
)

# ------------------ Identify Column Types ------------------
cat_cols = X.select_dtypes(include='object').columns
num_cols = X.select_dtypes(exclude='object').columns

# ------------------ Preprocessing ------------------
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols)
    ]
)

# ------------------ Train/Test Split ------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    stratify=y,
    random_state=42
)

# ------------------ Logistic Regression ------------------
model = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('logreg', LogisticRegression(max_iter=1000))
])

model.fit(X_train, y_train)

# ------------------ Predicted Probabilities ------------------
y_prob = model.predict_proba(X_test)[:, 1]

# ------------------ Evaluation Function ------------------
def evaluate_threshold(threshold):
    y_pred = (y_prob >= threshold).astype(int)
    cm = confusion_matrix(y_test, y_pred)

    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    tn, fp, fn, tp = cm.ravel()
    specificity = tn / (tn + fp)

    return cm, precision, recall, f1, specificity

# ------------------ Threshold = 0.5 ------------------
cm_05, p_05, r_05, f1_05, spec_05 = evaluate_threshold(0.5)
roc_auc = roc_auc_score(y_test, y_prob)

print("\n===== Threshold = 0.5 =====")
print("Confusion Matrix:\n", cm_05)
print(f"Precision: {p_05:.4f}")
print(f"Recall (Sensitivity): {r_05:.4f}")
print(f"Specificity: {spec_05:.4f}")
print(f"F1-score: {f1_05:.4f}")
print(f"ROC-AUC: {roc_auc:.4f}")

# ------------------ Optimized Threshold (Youden's J) ------------------
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
best_threshold = thresholds[np.argmax(tpr - fpr)]

cm_opt, p_opt, r_opt, f1_opt, spec_opt = evaluate_threshold(best_threshold)

print("\n===== Optimized Threshold =====")
print(f"Best Threshold: {best_threshold:.4f}")
print("Confusion Matrix:\n", cm_opt)
print(f"Precision: {p_opt:.4f}")
print(f"Recall (Sensitivity): {r_opt:.4f}")
print(f"Specificity: {spec_opt:.4f}")
print(f"F1-score: {f1_opt:.4f}")

# ------------------ Save probabilities.csv ------------------
output = pd.DataFrame({
    'RecordId': X_test.index,
    'Probability(yes)': y_prob,
    'PredictedLabel': (y_prob >= best_threshold).astype(int)
})

output.to_csv('probabilities.csv', index=False)
print("\nSaved probabilities.csv")