# -*- coding: utf-8 -*-
"""ML A1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Us1-jg6yqqsB69aPsdKhQ4jWlZHC_ljx
"""

# ============================================================
# Breast Cancer Diagnosis Classification Pipeline
# Dataset: Breast Cancer Wisconsin Diagnostic (UCI)
# Models: Logistic Regression, Decision Tree
# ============================================================

!pip install ucimlrepo

import numpy as np
import pandas as pd

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)


# 1. Load Dataset

breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17)

X = breast_cancer_wisconsin_diagnostic.data.features
y = breast_cancer_wisconsin_diagnostic.data.targets

# Convert target to 1D array
y = y.values.ravel()

print("Dataset loaded successfully")
print("Features shape:", X.shape)
print("Target distribution:\n", pd.Series(y).value_counts())


# 2. Train / Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# 3. Feature Scaling (Important for Logistic Regression)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# 4. Logistic Regression Model

log_reg = LogisticRegression(max_iter=500, random_state=42)
log_reg.fit(X_train_scaled, y_train)

# Predictions
y_train_pred_lr = log_reg.predict(X_train_scaled)
y_test_pred_lr = log_reg.predict(X_test_scaled)

# Errors
train_error_lr = 1 - accuracy_score(y_train, y_train_pred_lr)
test_error_lr = 1 - accuracy_score(y_test, y_test_pred_lr)

print("\n================ Logistic Regression =================")
print(f"Train Error: {train_error_lr:.4f}")
print(f"Test Error : {test_error_lr:.4f}")
print("Generalization Gap:", abs(train_error_lr - test_error_lr))

print("\nTest Metrics:")
print("Accuracy :", accuracy_score(y_test, y_test_pred_lr))
print("Precision:", precision_score(y_test, y_test_pred_lr, pos_label='M'))
print("Recall   :", recall_score(y_test, y_test_pred_lr, pos_label='M'))
print("F1-score :", f1_score(y_test, y_test_pred_lr, pos_label='M'))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_lr))


# 5. Decision Tree Model (Non-linear)

dt = DecisionTreeClassifier(
    max_depth=None,
    random_state=42
)

dt.fit(X_train, y_train)

# Predictions
y_train_pred_dt = dt.predict(X_train)
y_test_pred_dt = dt.predict(X_test)

# Errors
train_error_dt = 1 - accuracy_score(y_train, y_train_pred_dt)
test_error_dt = 1 - accuracy_score(y_test, y_test_pred_dt)

print("\n================ Decision Tree =================")
print(f"Train Error: {train_error_dt:.4f}")
print(f"Test Error : {test_error_dt:.4f}")
print("Generalization Gap:", abs(train_error_dt - test_error_dt))

print("\nTest Metrics:")
print("Accuracy :", accuracy_score(y_test, y_test_pred_dt))
print("Precision:", precision_score(y_test, y_test_pred_dt, pos_label='M'))
print("Recall   :", recall_score(y_test, y_test_pred_dt, pos_label='M'))
print("F1-score :", f1_score(y_test, y_test_pred_dt, pos_label='M'))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_dt))


# 6. Conclusion / Error Analysis

print("\n================ Conclusion =================")
print("""
Logistic Regression shows similar training and test errors, indicating good
generalization and low variance. Feature scaling played a crucial role in its
performance due to the magnitude differences across features.

The Decision Tree achieves near-zero training error but a higher test error,
indicating overfitting. This is expected because unpruned trees can memorize
training data and fail to generalize.

Relevant ML issues in this task:
1. Feature Scaling: Essential for gradient-based models like Logistic Regression.
2. Overfitting: Decision Trees without depth constraints overfit easily.
3. Feature Correlation: Many medical features are highly correlated, which
   can impact model stability.
4. Class Imbalance: Slight imbalance exists, so precision/recall are more
   informative than accuracy alone.
""")